"use client";

import { useCallback } from "react";

const cheatsheetContent = `# MCP Server Installation Quick Reference (2026)

## Per-Client Setup Commands

### Claude Desktop
1. Open \`claude_desktop_config.json\` (macOS: \`~/Library/Application Support/Claude/\`, Windows: \`%APPDATA%\\Claude\`).
2. Add under \`mcpServers\`:
\`\`\`json
{
  "mcpServers": {
    "server-name": {
      "command": "npx",
      "args": ["-y", "@scope/package"],
      "env": { "KEY": "value" }
    }
  }
}
\`\`\`
3. Save, fully quit & restart Claude.

### Cursor
1. Settings → MCP → Add New MCP Server.
2. Paste command (e.g., \`npx -y @scope/package\`) and env vars.
3. Save, reload if needed.

### Claude Code / VS Code (terminal)
\`\`\`bash
claude mcp add server-name -- npx -y @scope/package
\`\`\`
Configure env vars separately if required.

## Common Installation Errors
- **Invalid JSON** → Validate commas/braces.
- **npx not found** → Install Node.js LTS.
- **Credentials missing** → Double-check env block / token.
- **Server not showing** → Restart client completely.
- **Package not resolving** → Ensure correct package name.

## First Servers to Install
1. GitHub MCP Server (\`@github/github-mcp-server\`)
2. Context7 MCP (\`@upstash/context7-mcp-server\`)
3. Desktop Commander (\`desktop-commander\`)

---
Generated by MCPIndex – Free Quick Reference
`;

export function DownloadMcpInstallCheatsheet() {
  const handleDownload = useCallback(() => {
    const blob = new Blob([cheatsheetContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mcp-install-quick-ref.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-sm transition-colors shadow-lg shadow-purple-600/20"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5 5-5M12 15V3" />
      </svg>
      Download Free Install Cheat Sheet
    </button>
  );
}
