"use client";

import { useCallback } from "react";

const cheatsheetContent = `# MCP Terminology & Quick-Start (2026)

## Core Concepts
- **Model Context Protocol (MCP)**: Open standard for AI ↔ tool integration.
- **MCP Host**: App where user interacts (Claude Desktop, Cursor).
- **MCP Client**: Protocol layer inside host that speaks MCP.
- **MCP Server**: Exposes tools, resources, prompts (e.g., GitHub, files).
- **Tools**: Actions the AI can perform via MCP.
- **Resources**: Live data/context the server exposes.
- **Prompts**: Reusable interaction templates.

## MCP vs Function Calling
| Feature           | Function Calling        | MCP                         |
|-------------------|------------------------|-----------------------------|
| Scope             | Single app context     | Cross‑client/server reuse   |
| Reusability       | App‑specific           | Write once, use everywhere  |
| Best for          | Small tool workflows   | Large, multi‑tool ecosystems|

## Minimal Config Example
\`\`\`json
{
  "mcpServers": {
    "github": {
      "command": "npx",
      "args": ["-y", "@github/github-mcp-server"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "YOUR_TOKEN"
      }
    }
  }
}
\`\`\`

## Best Practices
1. Start with read‑only MCP servers.
2. Use least‑privilege API tokens.
3. Test with a simple prompt first (e.g., "List my repos").
4. Restart client after config changes.

---
Generated by MCPIndex – Free Developer Resource
`;

export function DownloadMcpIntroCheatsheet() {
  const handleDownload = useCallback(() => {
    const blob = new Blob([cheatsheetContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mcp-terminology-quickstart.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-sm transition-colors shadow-lg shadow-purple-600/20"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5 5-5M12 15V3" />
      </svg>
      Download Free MCP Cheat Sheet
    </button>
  );
}
