"use client";

import { useCallback } from "react";

const cheatsheetContent = `# GitHub MCP Authentication Cheat Sheet (2026)

## Recommended Token Scopes
| Scope      | Purpose                          |
|------------|----------------------------------|
| repo       | Private repos, full read/write   |
| read:org   | Organization membership & access |
| read:user  | Basic user account info          |

## Classic vs Fine-Grained Tokens
- **Classic PAT**: Easy setup, broad scopes. Good for local dev.
- **Fine-grained**: Restrict to specific repos. Safer but needs precise config.

## Common Errors & Fixes
1. **Private repos invisible** → Add \`repo\` scope or check fine-grained repo selection.
2. **Tools missing in Claude** → Token lacks required permissions. Re-check scopes.
3. **Issue/PR actions fail** → Token may need \`repo\` or \`write:org\` permissions.
4. **Token works in CLI but not MCP** → Verify \`GITHUB_PERSONAL_ACCESS_TOKEN\` env variable.
5. **Auth correct but Claude fails** → Restart Claude Desktop completely after config change.

## Quick Token Check Command
\`\`\`bash
curl -sI -H "Authorization: Bearer $GITHUB_PERSONAL_ACCESS_TOKEN" \\
https://api.github.com/user | grep -i x-oauth-scopes
\`\`\`

---
Generated by MCPIndex – Free Developer Resource
`;

export function DownloadGitHubAuthCheatsheet() {
  const handleDownload = useCallback(() => {
    const blob = new Blob([cheatsheetContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "github-mcp-auth-cheatsheet.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-sm transition-colors shadow-lg shadow-purple-600/20"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5 5-5M12 15V3" />
      </svg>
      Download Free Auth Cheat Sheet
    </button>
  );
}
