"use client";

import { useCallback } from "react";

const cheatsheetContent = `# GitHub MCP Server Setup Cheat Sheet (2026)

## Quick Configuration
\`\`\`json
{
  "mcpServers": {
    "github": {
      "command": "npx",
      "args": ["-y", "@github/github-mcp-server"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "YOUR_TOKEN"
      }
    }
  }
}
\`\`\`

## Token Scopes (Recommended Baseline)
| Scope     | Purpose                         |
|-----------|---------------------------------|
| repo      | Private repos, PRs, issues      |
| read:org  | Organization membership & access|
| read:user | Basic user profile info         |

## Setup Steps
1. Create a GitHub Personal Access Token (classic or fine-grained).
2. Open \`claude_desktop_config.json\` (macOS: \`~/Library/Application Support/Claude/\`, Windows: \`%APPDATA%\\Claude\`).
3. Paste the JSON block above, replacing \`YOUR_TOKEN\`.
4. Fully quit and restart Claude Desktop.
5. Test: "List my GitHub repositories."

## Common Errors & Fixes
- **Invalid JSON** → Check commas/braces.
- **Token missing/expired** → Verify token in env block.
- **Private repos invisible** → Add \`repo\` scope.
- **Tools missing** → Token permissions too narrow.
- **npx fails** → Install Node.js LTS.

## Test Prompts
- "List my GitHub repositories."
- "Show open pull requests."
- "Search for authentication middleware."

---
Generated by MCPIndex – Free Developer Resource
`;

export function DownloadGitHubSetupCheatsheet() {
  const handleDownload = useCallback(() => {
    const blob = new Blob([cheatsheetContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "github-mcp-setup-cheatsheet.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-sm transition-colors shadow-lg shadow-purple-600/20"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5 5-5M12 15V3" />
      </svg>
      Download Free Setup Cheat Sheet
    </button>
  );
}
