"use client";

import { useState } from "react";

export function DownloadGithubPromptsButton() {
  const [isDownloaded, setIsDownloaded] = useState(false);

  const handleDownload = () => {
    const promptVault = `# 🧠 Claude GitHub Prompt Vault (By MCPIndex)
# Copy and paste these directly into Claude Desktop, Claude Code, or Cursor.

---

## 1. The Ultimate PR Reviewer
Use this prompt when Claude is connected via GitHub MCP and you want a deep code review.

**Prompt:**
> You are a Senior Staff Engineer conducting a thorough code review. 
> Analyze the latest Pull Request. Focus on:
> 1. **Critical Issues:** Security vulnerabilities, data leaks, or logic errors that will break production.
> 2. **Performance:** Any bottlenecks, N+1 queries, or memory leaks.
> 3. **Best Practices:** Are design patterns followed? Is the code readable?
> Format your output strictly with "🔴 Critical", "🟡 Warning", and "🟢 Suggestion" bullet points.

---

## 2. The Issue Triage Agent
Use this when you have a backlog of issues and want Claude to organize them.

**Prompt:**
> Act as a Technical Project Manager. Read the last 10 open issues in this repository. 
> For each issue, classify it as: \`Bug\`, \`Feature\`, \`Tech Debt\`, or \`Question\`.
> Then, assign a priority level: \`P0\` (Critical/Down), \`P1\` (High), \`P2\` (Medium), \`P3\` (Low).
> Output a clean Markdown table with columns: Issue #, Title, Type, Priority, Reasoning.

---

## 3. The Changelog Generator
Use this after merging a PR to automatically update your CHANGELOG.md.

**Prompt:**
> Review the commits and the merged PR description. Generate a professional standard Keep a Changelog entry.
> Categorize changes under: \`Added\`, \`Changed\`, \`Deprecated\`, \`Removed\`, \`Fixed\`, \`Security\`.
> Do not invent features; only include what is explicitly mentioned in the PR/commits.

---

## 4. The CI/CD Debugger
Use this when a GitHub Actions workflow fails and you want Claude to fix it.

**Prompt:**
> A GitHub Actions workflow has failed. Read the latest workflow run logs. 
> Identify the exact step that failed, extract the error message, and explain the root cause in simple terms. 
> Then, provide the exact code snippet or YAML configuration needed to fix the workflow file. Do not guess; base your answer only on the logs.

---

## 5. The Release Notes Writer
Use this to write amazing release notes for your users or team.

**Prompt:**
> Analyze the merged Pull Requests since the last release tag. 
> Write engaging, user-friendly release notes. 
> Start with a high-level summary of the release theme.
> Group changes into "✨ New Features", "🐛 Bug Fixes", and "⚡ Performance".
> Avoid overly technical jargon; write it for the end-user.

---
*Generated by MCPIndex.dev - Find the best MCP servers at mcpindex.dev/tools*
`;

    const blob = new Blob([promptVault], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "Claude-GitHub-Prompt-Vault.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setIsDownloaded(true);
    setTimeout(() => setIsDownloaded(false), 3000);
  };

  return (
    <button
      onClick={handleDownload}
      className={`w-full sm:w-auto inline-flex items-center justify-center gap-3 px-8 py-4 rounded-xl text-base font-semibold transition-all duration-300 ${
        isDownloaded
          ? "bg-emerald-600 hover:bg-emerald-500 text-white"
          : "bg-white hover:bg-zinc-200 text-black shadow-lg shadow-white/10"
      }`}
    >
      {isDownloaded ? (
        <>
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
          Downloaded!
        </>
      ) : (
        <>
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
          Get 5 Free GitHub Prompts
        </>
      )}
    </button>
  );
}
